spring.application.name=spring_security_impl


spring.datasource.url=jdbc:postgresql://localhost:5433/userDB
spring.datasource.username=postgres
spring.datasource.password=0987654321


spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



jwt.secret=18eae8e932609b6a30e23d4cbb45a9a5d371a703dbde75d9a4544886ed1f7b5be2661c9615b57cdf6d2eac23966733eab7e97356c5e3a6e1e8e773febcba6b23
